CREATE TABLE `crm_naf_main` (
  `id` int(15) NOT NULL AUTO_INCREMENT,
  `initiator` varchar(200) DEFAULT NULL,
  `userid` int(20) NOT NULL,
  `emp_code` int(6) NOT NULL,
  `date` date NOT NULL,
  `post_comment` varchar(255) NOT NULL,
  `category_id` int(11) NOT NULL,
  `submitted_on` datetime NOT NULL,
  `submitted` int(1) NOT NULL,
  `pendingwithid` varchar(20) NOT NULL,
  `authorise` int(1) NOT NULL,
  `approved_date` datetime NOT NULL,
  `deleted` int(1) NOT NULL,
  `deleted_on` datetime NOT NULL,
  `eventdate` date DEFAULT NULL,
  `level` int(5) NOT NULL DEFAULT '0',
  `naf_no` varchar(50) NOT NULL,
  `naf_activity_name` varchar(100) NOT NULL,
  `naf_city` int(10) NOT NULL,
  `naf_proposed_venue` varchar(100) NOT NULL,
  `naf_estimate_no_participents` int(10) NOT NULL,
  `naf_start_date` date NOT NULL,
  `naf_end_date` date NOT NULL,
  `naf_objective_rational` text NOT NULL,
  `remarks` text,
  `quarter` int(5) DEFAULT NULL,
  `mode` int(5) DEFAULT NULL,
  `proposed_activity_count` int(11) DEFAULT NULL,
  `proposed_hcp_no` int(11) DEFAULT NULL,
  `proposed_activity` text,
  `proposed_objective` text,
  `rationale_remark` text,
  `lead_event` text,
  `medical_equipments` text,
  `deviation_amount` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `userid` (`userid`),
  KEY `emp_code` (`emp_code`),
  KEY `date` (`date`),
  KEY `pendingwithid` (`pendingwithid`),
  KEY `authorise` (`authorise`),
  KEY `deleted` (`deleted`)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=latin1;
